version: "3"
services:
  # To connect a lot of nodes easily
  kademliaEntry:
    build: .
    command: sh -c "./main entry"
    image: kadlab:latest
    stdin_open: true
    tty: true
    networks:
      - kademlia_network

  kademliaNodes:
    build: .
    command: sh -c "./main auto"
    image: kadlab:latest
    stdin_open: true
    tty: true
    deploy:
      mode: replicated
      replicas: 49
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 10s
    networks:
      - kademlia_network

networks:
  kademlia_network:
