version: "3"
services:

  # To connect a lot of nodes easily
  kademliaEntry:
    build:
      dockerfile: Dockerfile
      context: .
      args:
          ENTRY: true
    image: kadlabentry:latest
    stdin_open: true
    tty: true
    networks:
      - kademlia_network

  kademliaNodes:
    build:
      dockerfile: Dockerfile
      context: .
    image: kadlabauto:latest
    stdin_open: true
    tty: true
    deploy:
      mode: replicated
      replicas: 5
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 10s
    networks:
      - kademlia_network

networks:
  kademlia_network:
